---
abstract: 'Spy on objects to achieve test doubles (mock testing)'
author:
  - 'Oliver Charles'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.102343, CPAN::Meta::Converter version 2.102400'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-Magpie
requires:
  Devel::PartialDump: 0.13
  List::AllUtils: 0.02
  Moose: 1.14
  MooseX::Params::Validate: 0.14
  MooseX::Types::Moose: 0.21
  MooseX::Types::Structured: 0.21
  Set::Object: 1.28
  Sub::Exporter: 0.982
  Test::Builder: 0.96
  Test::Fatal: 0.003
  Test::More: 0.96
  aliased: 0.30
  namespace::autoclean: 0.09
version: 0.03
x_Dist_Zilla:
  plugins:
    -
      class: Dist::Zilla::Plugin::GatherDir
      name: '@Filter/GatherDir'
      version: 4.102343
    -
      class: Dist::Zilla::Plugin::PruneCruft
      name: '@Filter/PruneCruft'
      version: 4.102343
    -
      class: Dist::Zilla::Plugin::ManifestSkip
      name: '@Filter/ManifestSkip'
      version: 4.102343
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: '@Filter/MetaYAML'
      version: 4.102343
    -
      class: Dist::Zilla::Plugin::License
      name: '@Filter/License'
      version: 4.102343
    -
      class: Dist::Zilla::Plugin::Readme
      name: '@Filter/Readme'
      version: 4.102343
    -
      class: Dist::Zilla::Plugin::ExtraTests
      name: '@Filter/ExtraTests'
      version: 4.102343
    -
      class: Dist::Zilla::Plugin::ExecDir
      name: '@Filter/ExecDir'
      version: 4.102343
    -
      class: Dist::Zilla::Plugin::ShareDir
      name: '@Filter/ShareDir'
      version: 4.102343
    -
      class: Dist::Zilla::Plugin::MakeMaker
      name: '@Filter/MakeMaker'
      version: 4.102343
    -
      class: Dist::Zilla::Plugin::Manifest
      name: '@Filter/Manifest'
      version: 4.102343
    -
      class: Dist::Zilla::Plugin::TestRelease
      name: '@Filter/TestRelease'
      version: 4.102343
    -
      class: Dist::Zilla::Plugin::ConfirmRelease
      name: '@Filter/ConfirmRelease'
      version: 4.102343
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: '@Filter/UploadToCPAN'
      version: 4.102343
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: MetaConfig
      version: 4.102343
    -
      class: Dist::Zilla::Plugin::MetaJSON
      name: MetaJSON
      version: 4.102343
    -
      class: Dist::Zilla::Plugin::PkgVersion
      name: PkgVersion
      version: 4.102343
    -
      class: Dist::Zilla::Plugin::PodSyntaxTests
      name: PodSyntaxTests
      version: 4.102343
    -
      class: Dist::Zilla::Plugin::PodCoverageTests
      name: PodCoverageTests
      version: 4.102343
    -
      class: Dist::Zilla::Plugin::NoTabsTests
      name: NoTabsTests
      version: 0.01
    -
      class: Dist::Zilla::Plugin::Git::Check
      name: '@Git/Check'
      version: 1.102810
    -
      class: Dist::Zilla::Plugin::Git::Commit
      name: '@Git/Commit'
      version: 1.102810
    -
      class: Dist::Zilla::Plugin::Git::Tag
      name: '@Git/Tag'
      version: 1.102810
    -
      class: Dist::Zilla::Plugin::Git::Push
      name: '@Git/Push'
      version: 1.102810
    -
      class: Dist::Zilla::Plugin::PodWeaver
      name: PodWeaver
      version: 3.101641
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: runtime
          type: requires
      name: Prereqs
      version: 4.102343
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: runtime
          type: requires
      name: tests
      version: 4.102343
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: 4.102343
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: 4.102343
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: 4.102343
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: 4.102343
  zilla:
    class: Dist::Zilla::Dist::Builder
    config:
      is_trial: 0
    version: 4.102343
